-- This migration is intentionally empty.
-- The RLS policies were reset via a full SQL reset script run directly in Supabase.
-- See the new canonical policies in the reset script (animes_insert_admin, animes_update_admin, etc).
-- Managers do NOT have INSERT/UPDATE access to the animes table.
